import Foundation

let countryData = [
    ["iso_code": "AF", "country": "Afghanistan", "latitude": "34.00", "longitude": "68.00"],
    //["iso_code": "AX", "country": "Åland Islands"],
    ["iso_code": "AL", "country": "Albania", "latitude": "42.00", "longitude": "20.00"],
    ["iso_code": "DZ", "country": "Algeria", "latitude": "28.00", "longitude": "1.70"],
    //["iso_code": "AS", "country": "American Samoa", "latitude": "-14.27", "longitude": "-170.13"],
    ["iso_code": "AD", "country": "Andorra", "latitude": "42.55", "longitude": "1.60"],
    ["iso_code": "AO", "country": "Angola", "latitude": "-11.20", "longitude": "17.87"],
    //["iso_code": "AI", "country": "Anguilla"],
    //["iso_code": "AQ", "country": "Antarctica"],
    ["iso_code": "AG", "country": "Antigua and Barbuda", "latitude": "17.06", "longitude": "-61.80"],
    ["iso_code": "AR", "country": "Argentina", "latitude": "-38.42", "longitude": "-63.62"],
    ["iso_code": "AM", "country": "Armenia", "latitude": "40.07", "longitude": "45.04"],
    ["iso_code": "AW", "country": "Aruba", "latitude": "12.52", "longitude": "-69.97"],
    ["iso_code": "AU", "country": "Australia", "latitude": "-25.27", "longitude": "133.78"],
    ["iso_code": "AT", "country": "Austria", "latitude": "47.52", "longitude": "14.55"],
    ["iso_code": "AZ", "country": "Azerbaijan", "latitude": "40.14", "longitude": "47.58"],
    ["iso_code": "BS", "country": "Bahamas", "latitude": "25.03", "longitude": "-77.40"],
    ["iso_code": "BH", "country": "Bahrain", "latitude": "25.93", "longitude": "50.64"],
    ["iso_code": "BD", "country": "Bangladesh", "latitude": "23.68", "longitude": "90.36"],
    ["iso_code": "BB", "country": "Barbados", "latitude": "13.19", "longitude": "-59.54"],
    ["iso_code": "BY", "country": "Belarus", "latitude": "53.71", "longitude": "27.95"],
    ["iso_code": "BE", "country": "Belgium", "latitude": "50.85", "longitude": "4.35"],
    ["iso_code": "BZ", "country": "Belize", "latitude": "17.19", "longitude": "-88.50"],
    ["iso_code": "BJ", "country": "Benin", "latitude": "9.31", "longitude": "2.32"],
    ["iso_code": "BM", "country": "Bermuda", "latitude": "32.32", "longitude": "-64.76"],
    ["iso_code": "BT", "country": "Bhutan", "latitude": "27.51", "longitude": "90.43"],
    ["iso_code": "BO", "country": "Bolivia", "latitude": "-16.29", "longitude": "-63.59"],
    ["iso_code": "BQ", "country": "Bonaire"],
    ["iso_code": "BA", "country": "Bosnia and Herzegovina", "latitude": "43.92", "longitude": "17.68"],
    ["iso_code": "BW", "country": "Botswana", "latitude": "-22.33", "longitude": "24.68"],
    //["iso_code": "BV", "country": "Bouvet Island"],
    ["iso_code": "BR", "country": "Brazil", "latitude": "-14.24", "longitude": "-51.93"],
    //["iso_code": "IO", "country": "British Indian Ocean Territory"],
    ["iso_code": "BN", "country": "Brunei Darussalam", "latitude": "4.54", "longitude": "114.73"],
    ["iso_code": "BG", "country": "Bulgaria", "latitude": "42.73", "longitude": "25.49"],
    ["iso_code": "BF", "country": "Burkina Faso", "latitude": "12.24", "longitude": "-1.56"],
    ["iso_code": "BI", "country": "Burundi", "latitude": "-3.37", "longitude": "29.92"],
    ["iso_code": "KH", "country": "Cambodia", "latitude": "12.57", "longitude": "104.99"],
    ["iso_code": "CM", "country": "Cameroon", "latitude": "7.37", "longitude": "12.35"],
    ["iso_code": "CA", "country": "Canada", "latitude": "56.13", "longitude": "-106.35"],
    ["iso_code": "CV", "country": "Cape Verde", "latitude": "16.54", "longitude": "-23.04"],
    ["iso_code": "KY", "country": "Cayman Islands", "latitude": "19.51", "longitude": "-80.57"],
    ["iso_code": "CF", "country": "Central African Republic", "latitude": "6.61", "longitude": "20.94"],
    ["iso_code": "TD", "country": "Chad", "latitude": "15.45", "longitude": "18.73"],
    ["iso_code": "CL", "country": "Chile", "latitude": "-35.68", "longitude": "-71.54"],
    ["iso_code": "CN", "country": "China", "latitude": "35.86", "longitude": "104.20"],
    //["iso_code": "CX", "country": "Christmas Island"],
    //["iso_code": "CC", "country": "Cocos (Keeling) Islands"],
    ["iso_code": "CO", "country": "Colombia", "latitude": "4.57", "longitude": "-74.30"],
    ["iso_code": "KM", "country": "Comoros", "latitude": "-11.87", "longitude": "43.88"],
    ["iso_code": "CG", "country": "Congo", "latitude": "-0.23", "longitude": "15.83"],
    ["iso_code": "CD", "country": "Congo, the Democratic Republic of the", "latitude": "-4.04", "longitude": "21.76"],
    //["iso_code": "CK", "country": "Cook Islands", "latitude": "-21.24", "longitude": "-159.78"],
    ["iso_code": "CR", "country": "Costa Rica", "latitude": "9.75", "longitude": "-83.75"],
    ["iso_code": "CI", "country": "Côte d'Ivoire", "latitude": "7.54", "longitude": "-5.55"],
    ["iso_code": "HR", "country": "Croatia", "latitude": "45.10", "longitude": "15.20"],
    ["iso_code": "CU", "country": "Cuba", "latitude": "21.52", "longitude": "-80.41"],
    //["iso_code": "CW", "country": "Curaçao", "latitude": "12.17", "longitude": "-68.99"],
    ["iso_code": "CY", "country": "Cyprus", "latitude": "35.13", "longitude": "33.43"],
    ["iso_code": "CZ", "country": "Czech Republic", "latitude": "49.82", "longitude": "15.47"],
    ["iso_code": "DK", "country": "Denmark", "latitude": "56.26", "longitude": "9.50"],
    ["iso_code": "DJ", "country": "Djibouti", "latitude": "11.83", "longitude": "42.59"],
    ["iso_code": "DM", "country": "Dominica", "latitude": "15.41", "longitude": "-61.35"],
    ["iso_code": "DO", "country": "Dominican Republic", "latitude": "18.73", "longitude": "-70.16"],
    ["iso_code": "EC", "country": "Ecuador", "latitude": "-1.83", "longitude": "-78.18"],
    ["iso_code": "EG", "country": "Egypt", "latitude": "26.82", "longitude": "30.80"],
    ["iso_code": "SV", "country": "El Salvador", "latitude": "13.79", "longitude": "-88.90"],
    ["iso_code": "GQ", "country": "Equatorial Guinea", "latitude": "1.65", "longitude": "10.27"],
    ["iso_code": "ER", "country": "Eritrea", "latitude": "15.18", "longitude": "39.78"],
    ["iso_code": "EE", "country": "Estonia", "latitude": "58.59", "longitude": "25.01"],
    ["iso_code": "ET", "country": "Ethiopia", "latitude": "9.15", "longitude": "40.49"],
    //["iso_code": "FK", "country": "Falkland Islands (Malvinas)", "latitude": "-51.80", "longitude": "-59.15"],
    //["iso_code": "FO", "country": "Faroe Islands", "latitude": "61.89", "longitude": "-6.81"],
    ["iso_code": "FJ", "country": "Fiji", "latitude": "-16.58", "longitude": "179.42"],
    ["iso_code": "FI", "country": "Finland", "latitude": "61.92", "longitude": "25.75"],
    ["iso_code": "FR", "country": "France", "latitude": "46.22", "longitude": "2.21"],
    //["iso_code": "GF", "country": "French Guiana", "latitude": "3.93", "longitude": "-53.12"],
    //["iso_code": "PF", "country": "French Polynesia", "latitude": "-17.68", "longitude": "-149.41"],
    //["iso_code": "TF", "country": "French Southern Territories", "latitude": "-49.28", "longitude": "69.35"],
    ["iso_code": "GA", "country": "Gabon", "latitude": "-0.80", "longitude": "11.61"],
    ["iso_code": "GM", "country": "Gambia", "latitude": "13.44", "longitude": "-15.31"],
    ["iso_code": "GE", "country": "Georgia", "latitude": "42.32", "longitude": "43.36"],
    ["iso_code": "DE", "country": "Germany", "latitude": "51.17", "longitude": "10.45"],
    ["iso_code": "GH", "country": "Ghana", "latitude": "7.95", "longitude": "-1.02"],
    //["iso_code": "GI", "country": "Gibraltar", "latitude": "36.14", "longitude": "-5.35"],
    ["iso_code": "GR", "country": "Greece", "latitude": "39.07", "longitude": "21.82"],
    //["iso_code": "GL", "country": "Greenland", "latitude": "71.71", "longitude": "-42.60"],
    ["iso_code": "GD", "country": "Grenada", "latitude": "12.12", "longitude": "-61.68"],
    //["iso_code": "GP", "country": "Guadeloupe", "latitude": "16.18", "longitude": "-61.72"],
    //["iso_code": "GU", "country": "Guam", "latitude": "13.44", "longitude": "144.80"],
    ["iso_code": "GT", "country": "Guatemala", "latitude": "15.78", "longitude": "-90.23"],
    //["iso_code": "GG", "country": "Guernsey", "latitude": "49.47", "longitude": "-2.58"],
    ["iso_code": "GN", "country": "Guinea", "latitude": "9.95", "longitude": "-11.92"],
    ["iso_code": "GW", "country": "Guinea-Bissau", "latitude": "11.80", "longitude": "-15.18"],
    ["iso_code": "GY", "country": "Guyana", "latitude": "4.86", "longitude": "-58.93"],
    ["iso_code": "HT", "country": "Haiti", "latitude": "18.97", "longitude": "-72.29"],
    //["iso_code": "HM", "country": "Heard Island and McDonald Islands", "latitude": "-53.08", "longitude": "73.51"],
    ["iso_code": "VA", "country": "Holy See (Vatican City State)", "latitude": "41.90", "longitude": "12.45"],
    ["iso_code": "HN", "country": "Honduras", "latitude": "15.20", "longitude": "-86.24"],
    //["iso_code": "HK", "country": "Hong Kong", "latitude": "22.32", "longitude": "114.17"],
    ["iso_code": "HU", "country": "Hungary", "latitude": "47.16", "longitude": "19.50"],
    ["iso_code": "IS", "country": "Iceland", "latitude": "64.96", "longitude": "-19.02"],
    ["iso_code": "IN", "country": "India", "latitude": "20.59", "longitude": "78.96"],
    ["iso_code": "ID", "country": "Indonesia", "latitude": "-2.97", "longitude": "104.76"],
    ["iso_code": "IR", "country": "Iran", "latitude": "32.43", "longitude": "53.69"],
    ["iso_code": "IQ", "country": "Iraq", "latitude": "33.23", "longitude": "43.68"],
    ["iso_code": "IE", "country": "Ireland", "latitude": "53.41", "longitude": "-8.24"],
    //["iso_code": "IM", "country": "Isle of Man", "latitude": "54.24", "longitude": "-4.55"],
    ["iso_code": "IL", "country": "Israel", "latitude": "31.12", "longitude": "35.22"],
    ["iso_code": "IT", "country": "Italy", "latitude": "41.87", "longitude": "12.57"],
    ["iso_code": "JM", "country": "Jamaica", "latitude": "18.11", "longitude": "-77.30"],
    ["iso_code": "JP", "country": "Japan", "latitude": "36.20", "longitude": "138.25"],
    //["iso_code": "JE", "country": "Jersey", "latitude": "49.21", "longitude": "-2.13"],
    ["iso_code": "JO", "country": "Jordan", "latitude": "30.59", "longitude": "36.00"],
    ["iso_code": "KZ", "country": "Kazakhstan", "latitude": "48.00", "longitude": "68.00"],
    ["iso_code": "KE", "country": "Kenya", "latitude": "1.00", "longitude": "38.00"],
    ["iso_code": "KI", "country": "Kiribati", "latitude": "1.87", "longitude": "173.01"],
    ["iso_code": "KP", "country": "North Korea", "latitude": "40.00", "longitude": "127.00"],
    ["iso_code": "KR", "country": "South Korea", "latitude": "36.00", "longitude": "128.00"],
    ["iso_code": "KW", "country": "Kuwait", "latitude": "29.50", "longitude": "47.75"],
    ["iso_code": "KG", "country": "Kyrgyzstan", "latitude": "41.00", "longitude": "75.00"],
    ["iso_code": "LA", "country": "Lao People's Democratic Republic", "latitude": "18.00", "longitude": "105.00"],
    ["iso_code": "LV", "country": "Latvia", "latitude": "57.00", "longitude": "25.00"],
    ["iso_code": "LB", "country": "Lebanon", "latitude": "33.83", "longitude": "35.83"],
    ["iso_code": "LS", "country": "Lesotho", "latitude": "-29.50", "longitude": "28.50"],
    ["iso_code": "LR", "country": "Liberia", "latitude": "6.50", "longitude": "-9.50"],
    ["iso_code": "LY", "country": "Libya", "latitude": "25.00", "longitude": "17.00"],
    ["iso_code": "LI", "country": "Liechtenstein", "latitude": "47.16", "longitude": "9.56"],
    ["iso_code": "LT", "country": "Lithuania", "latitude": "56.00", "longitude": "24.00"],
    ["iso_code": "LU", "country": "Luxembourg", "latitude": "49.75", "longitude": "6.17"],
    //["iso_code": "MO", "country": "Macao", "latitude": "22.17", "longitude": "113.55"],
    ["iso_code": "MK", "country": "Macedonia", "latitude": "41.83", "longitude": "22.00"],
    ["iso_code": "MG", "country": "Madagascar", "latitude": "-20.00", "longitude": "47.00"],
    ["iso_code": "MW", "country": "Malawi", "latitude": "-13.50", "longitude": "34.00"],
    ["iso_code": "MY", "country": "Malaysia", "latitude": "2.50", "longitude": "112.50"],
    ["iso_code": "MV", "country": "Maldives", "latitude": "3.25", "longitude": "73.00"],
    ["iso_code": "ML", "country": "Mali", "latitude": "17.00", "longitude": "-4.00"],
    ["iso_code": "MT", "country": "Malta", "latitude": "35.92", "longitude": "14.42"],
    ["iso_code": "MH", "country": "Marshall Islands", "latitude": "9.00", "longitude": "168.00"],
    //["iso_code": "MQ", "country": "Martinique", "latitude": "14.67", "longitude": "-61.00"],
    ["iso_code": "MR", "country": "Mauritania", "latitude": "20.00", "longitude": "-12.00"],
    ["iso_code": "MU", "country": "Mauritius", "latitude": "-20.28", "longitude": "57.55"],
    //["iso_code": "YT", "country": "Mayotte", "latitude": "-12.83", "longitude": "45.17"],
    ["iso_code": "MX", "country": "Mexico", "latitude": "23.00", "longitude": "-102.00"],
    ["iso_code": "FM", "country": "Micronesia", "latitude": "6.92", "longitude": "158.25"],
    ["iso_code": "MD", "country": "Moldova", "latitude": "47.00", "longitude": "29.00"],
    ["iso_code": "MC", "country": "Monaco", "latitude": "43.73", "longitude": "7.42"],
    ["iso_code": "MN", "country": "Mongolia", "latitude": "46.00", "longitude": "105.00"],
    ["iso_code": "ME", "country": "Montenegro", "latitude": "42.77", "longitude": "19.24"],
    //["iso_code": "MS", "country": "Montserrat", "latitude": "16.75", "longitude": "-62.20"],
    ["iso_code": "MA", "country": "Morocco", "latitude": "32.00", "longitude": "-5.00"],
    ["iso_code": "MZ", "country": "Mozambique", "latitude": "-18.25", "longitude": "35.00"],
    ["iso_code": "MM", "country": "Myanmar", "latitude": "22.00", "longitude": "98.00"],
    ["iso_code": "NA", "country": "Namibia", "latitude": "-22.00", "longitude": "17.00"],
    //["iso_code": "NR", "country": "Nauru", "latitude": "-0.53", "longitude": "166.92"],
    ["iso_code": "NP", "country": "Nepal", "latitude": "28.00", "longitude": "84.00"],
    ["iso_code": "NL", "country": "Netherlands", "latitude": "52.50", "longitude": "5.75"],
    //["iso_code": "NC", "country": "New Caledonia", "latitude": "-21.50", "longitude": "165.50"],
    ["iso_code": "NZ", "country": "New Zealand", "latitude": "-41.00", "longitude": "174.00"],
    ["iso_code": "NI", "country": "Nicaragua", "latitude": "13.00", "longitude": "-85.00"],
    ["iso_code": "NE", "country": "Niger", "latitude": "16.00", "longitude": "8.00"],
    ["iso_code": "NG", "country": "Nigeria", "latitude": "9.08", "longitude": "8.68"],
    ["iso_code": "NO", "country": "Norway", "latitude": "60.47", "longitude": "8.47"],
    ["iso_code": "OM", "country": "Oman", "latitude": "20.59", "longitude": "56.10"],
    ["iso_code": "PK", "country": "Pakistan", "latitude": "30.38", "longitude": "69.35"],
    ["iso_code": "PS", "country": "Palestine", "latitude": "31.95", "longitude": "35.23"],
    ["iso_code": "PA", "country": "Panama", "latitude": "8.97", "longitude": "-79.53"],
    ["iso_code": "PG", "country": "Papua New Guinea", "latitude": "-6.31", "longitude": "143.96"],
    ["iso_code": "PY", "country": "Paraguay", "latitude": "-23.44", "longitude": "-58.44"],
    ["iso_code": "PE", "country": "Peru", "latitude": "-9.19", "longitude": "-75.02"],
    ["iso_code": "PH", "country": "Philippines", "latitude": "12.88", "longitude": "121.77"],
    ["iso_code": "PL", "country": "Poland", "latitude": "51.92", "longitude": "19.14"],
    ["iso_code": "PT", "country": "Portugal", "latitude": "39.40", "longitude": "-8.22"],
    ["iso_code": "QA", "country": "Qatar", "latitude": "25.35", "longitude": "51.19"],
    ["iso_code": "RO", "country": "Romania", "latitude": "45.94", "longitude": "24.97"],
    ["iso_code": "RU", "country": "Russian Federation", "latitude": "61.52", "longitude": "105.32"],
    ["iso_code": "RW", "country": "Rwanda", "latitude": "-1.94", "longitude": "29.87"],
    ["iso_code": "VC", "country": "Saint Vincent and the Grenadines", "latitude": "12.97", "longitude": "-61.29"],
    ["iso_code": "WS", "country": "Samoa", "latitude": "-13.76", "longitude": "-172.10"],
    ["iso_code": "SM", "country": "San Marino", "latitude": "43.94", "longitude": "12.46"],
    ["iso_code": "ST", "country": "Sao Tome and Principe", "latitude": "0.19", "longitude": "6.74"],
    ["iso_code": "SA", "country": "Saudi Arabia", "latitude": "23.89", "longitude": "45.08"],
    ["iso_code": "SN", "country": "Senegal", "latitude": "14.50", "longitude": "-14.45"],
    ["iso_code": "RS", "country": "Serbia", "latitude": "44.02", "longitude": "21.01"],
    ["iso_code": "SC", "country": "Seychelles", "latitude": "-4.68", "longitude": "55.49"],
    ["iso_code": "SL", "country": "Sierra Leone", "latitude": "8.46", "longitude": "-11.78"],
    ["iso_code": "SG", "country": "Singapore", "latitude": "1.35", "longitude": "103.82"],
    ["iso_code": "SK", "country": "Slovakia", "latitude": "48.67", "longitude": "19.70"],
    ["iso_code": "SI", "country": "Slovenia", "latitude": "46.15", "longitude": "14.99"],
    ["iso_code": "SB", "country": "Solomon Islands", "latitude": "-9.19", "longitude": "160.97"],
    ["iso_code": "SO", "country": "Somalia", "latitude": "5.15", "longitude": "46.20"],
    ["iso_code": "ZA", "country": "South Africa", "latitude": "-30.56", "longitude": "22.94"],
    ["iso_code": "SS", "country": "South Sudan", "latitude": "6.88", "longitude": "31.31"],
    ["iso_code": "ES", "country": "Spain", "latitude": "40.46", "longitude": "-3.75"],
    ["iso_code": "LK", "country": "Sri Lanka", "latitude": "7.87", "longitude": "80.77"],
    ["iso_code": "SD", "country": "Sudan", "latitude": "12.86", "longitude": "30.22"],
    ["iso_code": "SR", "country": "Suriname", "latitude": "3.92", "longitude": "-56.03"],
    ["iso_code": "SZ", "country": "Swaziland", "latitude": "-26.52", "longitude": "31.47"],
    ["iso_code": "SE", "country": "Sweden", "latitude": "60.13", "longitude": "18.64"],
    ["iso_code": "CH", "country": "Switzerland", "latitude": "46.82", "longitude": "8.23"],
    ["iso_code": "SY", "country": "Syrian Arab Republic", "latitude": "34.80", "longitude": "38.99"],
    ["iso_code": "TW", "country": "Taiwan", "latitude": "23.70", "longitude": "121.00"],
    ["iso_code": "TJ", "country": "Tajikistan", "latitude": "38.86", "longitude": "71.28"],
    ["iso_code": "TZ", "country": "Tanzania", "latitude": "-6.37", "longitude": "34.89"],
    ["iso_code": "TH", "country": "Thailand", "latitude": "15.87", "longitude": "100.99"],
    ["iso_code": "TL", "country": "Timor-Leste", "latitude": "-8.87", "longitude": "125.73"],
    ["iso_code": "TG", "country": "Togo", "latitude": "8.62", "longitude": "0.82"],
    ["iso_code": "TO", "country": "Tonga", "latitude": "-21.18", "longitude": "-175.20"],
    ["iso_code": "TT", "country": "Trinidad and Tobago", "latitude": "10.69", "longitude": "-61.22"],
    ["iso_code": "TN", "country": "Tunisia", "latitude": "33.89", "longitude": "9.54"],
    ["iso_code": "TR", "country": "Turkey", "latitude": "38.96", "longitude": "35.24"],
    ["iso_code": "TM", "country": "Turkmenistan", "latitude": "38.97", "longitude": "59.56"],
    ["iso_code": "UG", "country": "Uganda", "latitude": "1.37", "longitude": "32.29"],
    ["iso_code": "UA", "country": "Ukraine", "latitude": "48.38", "longitude": "31.17"],
    ["iso_code": "AE", "country": "United Arab Emirates", "latitude": "23.42", "longitude": "53.85"],
    ["iso_code": "GB", "country": "United Kingdom", "latitude": "55.38", "longitude": "-3.44"],
    ["iso_code": "US", "country": "United States", "latitude": "37.09", "longitude": "-95.71"],
    ["iso_code": "UY", "country": "Uruguay", "latitude": "-32.52", "longitude": "-55.77"],
    ["iso_code": "UZ", "country": "Uzbekistan", "latitude": "41.38", "longitude": "64.59"],
    ["iso_code": "VU", "country": "Vanuatu", "latitude": "-15.38", "longitude": "166.96"],
    ["iso_code": "VE", "country": "Venezuela", "latitude": "6.42", "longitude": "-66.59"],
    ["iso_code": "VN", "country": "Vietnam", "latitude": "14.06", "longitude": "108.28"],
    ["iso_code": "YE", "country": "Yemen", "latitude": "15.55", "longitude": "48.52"],
    ["iso_code": "ZM", "country": "Zambia", "latitude": "-13.13", "longitude": "27.85"],
    ["iso_code": "ZW", "country": "Zimbabwe", "latitude": "-19.02", "longitude": "29.15"]
]

